using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EulerProblems_
{
    /*Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
    find the sum of the even-valued terms.*/
    class problem2
    {
        List<int> myList = new List<int>();
        public problem2()
        {
            int i = 1;
            int j = 2;
            int k = 3;
            int multiply = 2;
            myList.Add(i);
            myList.Add(j);
            while (true)
            {
                myList.Add(k);
                i = j;
                j = k;
                k = i + j;
                if (k % 2 == 0)
                {
                    multiply += k;
                }
                if (k > 4000000)
                {
                    break;
                }
            }
            Console.WriteLine(multiply);
        }

    }
}
